---

image: gitlab.tools.in.pan-net.eu:4567/docker-images/docker-ansible

stages:
  - setup
  - smoke
  - review
  - qa
  - staging
  - deploy

before_script:
  - echo "Running $CI_JOB_NAME in stage $CI_JOB_STAGE"
  - env | sort | tee /tmp/$CI_JOB_STAGE-$CI_JOB_NAME.env
  - pwd; pwd -P;

setup_env:
  stage: setup
  script:
    - echo "Setting up the ENV"
    - cicd/env-setup

# ---- Sanity Testing ----

smoke_test:
  stage: smoke
  script:
    - export ENVS='smoke'
    - echo "Smoke testing the app"
    - cicd/qa-test-harness smoke

# ---- Feature Development ----

deploy_feature_review:
  stage: review
  script:
    - echo "Deploying the review environment for review/$CI_COMMIT_REF_NAME"
    - cicd/deploy review/$CI_COMMIT_REF_NAME
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url:  http://review-board.ao.in.pan-net.eu/?id=
  only:
    - /feature\/.+/

# ---- QA -----

deploy_qa:
  stage: qa
  script:
    - export ENVS='ao-qa-ic-hrzagt1,ao-qa-ic-skbrab1'
    - echo "Deploy to $ENVS ($CI_JOB_NAME in $CI_JOB_STAGE)"
    - cicd/deploy qa
  environment:
    name: qa
    url:  https://ao-qa-ic-hrzagt1.ao.in.pan-net.eu/status
  only:
    - develop

integration_test:
  stage: qa
  script:
    - export ENVS="ao-qa-ic-skbrab1"
    - echo "Invoking systems test ($CI_JOB_NAME in $CI_JOB_STAGE)"
    - cicd/qa-test-harness integration
  environment:
    name: qa/cit/status/$CI_COMMIT_REF_NAME
    url:  https://ao-qa-ic-hrzagt1.ao.in.pan-net.eu/status?id=cit
  only:
    - develop

systems_test:
  stage: qa
  script:
    - export ENVS='ao-qa-ic-skbrab1'
    - echo "Invoking systems test ($CI_JOB_NAME in $CI_JOB_STAGE)"
    - cicd/qa-test-harness system
  environment:
    name: qa/st/status/$CI_COMMIT_REF_NAME
    url:  https://ao-qa-ic-hrzagt1.ao.in.pan-net.eu/status?id=sit
  only:
    - develop

# ---- Staging -----

deploy_staging:
  stage: staging
  script:
    - export ENVS='ao-stag-ic-hrzagt1,ao-stag-ic-skbrab1'
    - echo "Deploy to $ENVS ($CI_JOB_NAME in $CI_JOB_STAGE)"
    - cicd/deploy staging
  environment:
    name: staging
    url:  https://ao-stag-ic-hrzagt1.ao.in.pan-net.eu/status
  only:
    - /release\/.+/
    - /hotfix\/.+/

regression_test:
  stage: staging
  script:
    - export ENVS='ao-stag-ic-hrzagt1,ao-stag-ic-skbrab1'
    - echo "Invoking systems test ($CI_JOB_NAME in $CI_JOB_STAGE)"
    - cicd/qa-test-harness rt
  environment:
    name: qa/rt/status
    url:  https://dashboard.ao.in.pan-net.eu/status?id=staging
  only:
    - /release\/.+/
    - /hotfix\/.+/

end2end_test:
  stage: staging
  script:
    - export ENVS='ao-stag-ic-hrzagt1,ao-stag-ic-skbrab1'
    - echo "Invoking systems test ($CI_JOB_NAME in $CI_JOB_STAGE)"
    - cicd/qa-test-harness e2e
  environment:
    name: qa/e2e/$CI_COMMIT_REF_NAME
    url:  https://dashboard.ao.in.pan-net.eu/status?id=staging
  only:
    - /release\/.+/
    - /hotfix\/.+/

# ---- Release ----

deploy_release_review:
  stage: review
  script:
    - echo "Deploying the review environment for review/$CI_COMMIT_REF_NAME"
    - cicd/deploy review/$CI_COMMIT_REF_NAME
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url:  http://review-board.ao.in.pan-net.eu/?id=
  only:
    - /release\/.+/
  when: manual

# ---- Production -----

deploy_production:
  stage: deploy
  script:
    - export ENVS='ao-prod-ic-hrzagt1,ao-prod-ic-hrbudb1,ao-prod-ic-plwarb1,ao-prod-ic-skbrab1'
    - echo "Deploy to $ENVS ($CI_JOB_NAME in $CI_JOB_STAGE)"
    - cicd/deploy $CI_ENVIRONMENT_NAME
  environment:
    name: production
    url:  https://dashboard.ao.in.pan-net.eu/status?id=production
  when: manual
  only:
    - master

